[package]
name = "Advent2024"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
regex = "1.10.6"
nom = "7.1.3"
num = "0.4.3"
rustc-hash = "2.0.0"
nohash-hasher = "0.2.0"

[dev-dependencies]
rstest = "0.22.0"